# Tests need nothing but Go. go.work is generated by scripts/work.sh instead
# of committed, and regenerated whenever a go.mod changes. make release
# VERSION=vX.Y.Z tags every module at that version (see CONTRIBUTING.md).
.PHONY: test release

test: go.work
	go test -race github.com/linzeyan/loadconf/...

go.work: $(wildcard */go.mod */*/go.mod)
	./scripts/work.sh

release:
	./scripts/release.sh $(VERSION)
